export const DEFAULT_THEME = {
  colorPrimary: '#1E3A8A',
  colorSecondary: '#b8860b',
  colorBackground: '#f9f7f4',
  colorSurface: '#ffffff',
  colorText: '#1a1a1a',
  colorTextMuted: '#6b7280',
  btnAddToCartBg: '#1E3A8A',
  btnAddToCartText: '#ffffff',
  btnCheckoutBg: '#b8860b',
  btnCheckoutText: '#ffffff',
  btnRadius: 8,
  btnCheckoutShape: 'rounded',
  cardRadius: 12,
  cardShadow: 'md',
  cardPadding: 16,
  cardGap: 24,
  cardImgHeight: 220,
  sectionPadding: 48,
  containerMaxWidth: 1280,
  fontFamily: 'inherit',
  fontSizeBase: 16,
};

export type ThemeConfig = typeof DEFAULT_THEME;