export const CATS = [
  'הכל',
  'מזוזות',
  'תפילין',
  'מגילות',
  'ספרי תורה',
  'יודאיקה',
  'מתנות',
  'בר מצווה',
  'חגים ומועדים',
  'סט טלית תפילין',
  'קלפים',
];

export const NAV_ITEMS: { label: string; cat: string | null; action: string | null }[] = [
  { label: '🔥 מבצעי היום',       cat: null,             action: null },
  { label: 'מזוזות',              cat: 'מזוזות',         action: null },
  { label: 'תפילין',              cat: 'תפילין',         action: null },
  { label: 'מגילות',              cat: 'מגילות',         action: null },
  { label: 'ספרי תורה',           cat: 'ספרי תורה',      action: null },
  { label: 'יודאיקה',             cat: 'יודאיקה',        action: null },
  { label: '🎁 מתנות',            cat: 'מתנות',          action: null },
  { label: '✡️ חגים ומועדים',     cat: 'חגים ומועדים',  action: null },
  { label: '🎉 בר מצווה',         cat: 'בר מצווה',       action: null },
  { label: '📜 קלפים',            cat: 'קלפים',          action: null },
  { label: '✍️ הסופרים שלנו',     cat: null,             action: 'soferim' },
  { label: '🌟 הצטרף לפלטפורמה', cat: null,             action: 'join' },
  { label: '🟦 חבד שליחים',       cat: null,             action: 'shluchim' },
  { label: 'סט טלית תפילין',      cat: 'סט טלית תפילין', action: null },
];